@baseUrl = http://localhost:3000

### Try to login an unknow user
POST {{baseUrl}}/auths/login
Content-Type: application/json

{
    "username":"unknown",
    "password":"admin"
}

### RANKING
GET {{baseUrl}}/ranks
Content-Type: application/json


### Login the default admin
POST {{baseUrl}}/auths/login
Content-Type: application/json

{
    "username":"admin",
    "password":"admin"
}


### Create the manager user
POST {{baseUrl}}/auths/register
Content-Type: application/json

{
    "username":"manager",
    "password":"manager"
}

### Login the manager user
POST {{baseUrl}}/auths/login
Content-Type: application/json

{
    "username":"manager",
    "password":"manager"
}

### Login the test2 user
POST {{baseUrl}}/auths/login
Content-Type: application/json

{
    "username":"test2",
    "password":"test2"
}

### PATCH
PATCH {{baseUrl}}/users/1
Content-Type: application/json

{
    "gamesPlayed": 2,
    "gamesLost": 2,
    "gamesWon": 0
}